version: "3.9"

services:
  server:
    build: .
    depends_on:
      - database
    networks: 
      - default
    environment:
      STAGE: test
    ports:
    - 5000:5000
    restart: always
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - default
    ports:
      - "5050:80"